services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todoadmin
      POSTGRES_PASSWORD: todopassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
