server:
  host: ${APP_HOST}
  port: ${APP_PORT}

spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway owns schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: "0gna/U4F7EkjNF0bIEcGyyhaGbCGI3t703mWoUr/0ro="
  expiration-hours: 6
