spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: todoadmin
    password: todopassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway owns schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: "0gna/U4F7EkjNF0bIEcGyyhaGbCGI3t703mWoUr/0ro="
  expiration-hours: 6
